on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  main:
    uses: Qteal/runbooks/.github/workflows/update.yml@reverse-eol
    with:
      dists-json: '["bionic", "focal", "jammy"]'
      version: ${{ inputs.version }}
    secrets: inherit
